import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/en/');
  await page.getByRole('link', { name: 'เสื้อแจ็ตเก็ต-ที่ระลึก 60 ปี มข' }).click();
  await page.getByRole('button', { name: ' Add to cart' }).click();
  await page.getByRole('link', { name: ' Proceed to checkout' }).click();
  await page.getByRole('link', { name: 'Proceed to checkout' }).click();
  await page.getByLabel('Mrs.').check();
  await page.getByLabel('First name').click();
  await page.getByLabel('First name').fill('mimi');
  await page.getByLabel('Last name').click();
  await page.getByLabel('Last name').fill('momoy');
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('kuga.sunt2001@gmail.com');
  await page.getByRole('textbox', { name: 'Password input' }).click();
  await page.getByRole('textbox', { name: 'Password input' }).fill('Tawan088086');
  await page.getByPlaceholder('MM/DD/YYYY').click();
  await page.getByPlaceholder('MM/DD/YYYY').fill('02/02/2002');
  await page.getByText(' Receive offers from our').click();
  await page.getByText(' I agree to the terms and').click();
  await page.getByText(' Sign up for our').click();
  await page.getByText(' Customer data privacyThe').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Alias').click();
  await page.getByLabel('Alias').fill('moop');
  await page.getByLabel('Company').click();
  await page.getByLabel('Company').fill('bbcv');
  await page.getByLabel('Address', { exact: true }).click();
  await page.getByLabel('Address', { exact: true }).fill('98/75 hdd');
  await page.getByLabel('Address Complement').click();
  await page.getByLabel('Address Complement').fill('koko');
  await page.getByLabel('City').click();
  await page.getByLabel('City').fill('babana');
  await page.getByLabel('State').selectOption('4');
  await page.getByLabel('Zip/Postal Code').click();
  await page.getByLabel('Zip/Postal Code').fill('33120');
  await page.getByLabel('Phone').click();
  await page.getByLabel('Phone').fill('0998855458');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('#js-delivery div').filter({ hasText: 'My carrier Delivery next day' }).nth(2).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Pay by Cash on Delivery').check();
  await page.getByLabel('I agree to the terms of').check();
  await page.getByRole('button', { name: 'Place order' }).click();
  await page.getByRole('link', { name: 'Orders' }).click();
});